# Literature study

As mentioned in the introduction, scientific literature on candlestick patterns is not very extensive. The two main topics of research are detection of candlestick patterns, and the evaluation of the predictive power of candlestick patterns. With regards to detection, the research is split in two approaches: a purely logic/rule-based approach or a machine learning-based approach. In recent years, the machine learning approach seems to be more popular. For evaluation, quite a number of methodologies have been proposed in the literature, with varying results. Some authors conclude that candlestick patterns have significant predictive power, whereas others conclude the opposite. One of the earliest studies by Caginalp and Laurent find statistical significance for eight patterns on the S&P 500 [-@caginalp1998]. Goo, Chen and Chang find significant average returns for most of the 26 patterns they study by making use of a *stop-loss* strategy on the Taiwanese stock market [-@goo2007]. Shiu and Lu find similar results on the Taiwanese market [-@shiu2011]. Others find no evidence of any predictive power. Fock, Klein and Zwergel analyse German futures and bonds, but find no significant returns. They try to improve their results through the use of additional technical indicators, such as momentum, moving average and relative strength index, but still find no significance [-@fock2005]. Marshall, Young and Rose employ a bootstrap methodology, but do not find significant returns [-@marshall2006]. Marshall, Young and Cahan make use of a similar technique on the Japanese market, but again find negative results [-@marshall2008]. With the exception of [-@fock2005], all the papers mentioned thus far make use of daily candlesticks. Our goal in this thesis is to study the predictive power of candlestick patterns on intraday data, as in [-@fock2005].

As is evident from the above, the different methodologies and patterns that are analysed as well as different definitions of candlestick patterns make it difficult to compare results of different authors and arrive at definitive conclusion as to whether candlestick patterns have any predictive power. Some efforts of standardization have been made however. Hu, Si, Fong and Lau formally define 103 candlestick patterns through the use of first-order logic, which will be used throughout this thesis [-@hu2019]. One matter of debate not settled in [-@hu2019], are classification of candlestick length, as some candlestick patterns call for "short", "normal", "tall"... candles. Etschberger, Fock, Klein and Zwergel define these lengths rigorously through percentiles, which we will again use in this thesis [-@etschberger2006]. Some candlestick patterns also call for specific lengths of the shadows, but for this the aforementioned percentiles can also be used.

With regards to evaluation and testing of predictive power, many methods have been proposed as well. One of the most common ones is a simple buy-and-hold strategy. However, as Fock, Klein and Zwergel note, this method is not a good benchmark in the short-term time horizon, as this implies frequent trading. Instead, they employ a set 30-minute holding time and compare this to randomized buy or sell signals. More involved methods of evaluation have been proposed as well, for example, Lu, Shiu and Liu make use of a variable holding period by buying when detecting a candlestick that is said to be a buy signal and selling when they detect an opposite signal. In this thesis, an adapted version of the *stop-loss* strategy will be used.[^02-literature-1]

[^02-literature-1]: For now, in the future other methods will definitely be used as well.
